.gitignore
ec/provider.go
ec/provider_config.go

EC Provider refactoring to use new ConfigureContextFunc
The change will refactor the EC provider code to use new ConfigureContextFunc which provides better diagnosis capabilities.
https://github.com/elastic/terraform-provider-ec/issues/34
Use the updated terraform sdk functionalities.
Locally by consuming the new provider and creating resources at Elastic cloud.

provider: Use ConfigureContextFunc

---

ec/ecresource/deployment.go
ec/ecresource/deploymentresource/create.go
ec/ecresource/deploymentresource/delete.go
ec/ecresource/deploymentresource/read.go
ec/ecresource/deploymentresource/update.go

This change refactors deployment create method to use the latest terraform SDK 2 resource manage functions.
in common each new functions returns diagnostics details allowing developers to build a list of warnings and errors to be presented to the Terraform user.
Enchancement #34
How Has This Been Tested?
make tests
Refactoring of code.

framework: Refactor CRUD operations to use Context

---

ec/acc/deployment_checks_test.go

Removes the acceptance `deployment.Healthy` since it creates a lot of
instability in the acceptance test results.
Resolves #38

acc: Remove deployment.Healthy check

---

docs/datasources/ec_deployment.md

Amends documentation to match the ec_deployment datasource schema.

docs: Amend ec_deployment datasource match schema

---

build/Makefile.test
ec/acc/acc_prereq.go
ec/ecdatasource/deploymentdatasource/datasource.go
ec/ecdatasource/deploymentdatasource/state/flatteners_apm.go
ec/ecdatasource/deploymentdatasource/state/flatteners_elasticsearch.go
ec/ecdatasource/deploymentdatasource/state/flatteners_enterprise_search.go
ec/ecdatasource/deploymentdatasource/state/flatteners_kibana.go
ec/ecresource/deploymentresource/apmstate/apm_expanders.go
ec/ecresource/deploymentresource/apmstate/apm_flatteners.go
ec/ecresource/deploymentresource/deploymentstate/traffic_filter.go
ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_expanders.go
ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_flatteners.go
ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_expanders.go
ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_flatteners.go
ec/ecresource/deploymentresource/expanders.go
ec/ecresource/deploymentresource/flatteners.go
ec/ecresource/deploymentresource/kibanastate/kibana_expanders.go
ec/ecresource/deploymentresource/kibanastate/kibana_flatteners.go
ec/provider.go
go.mod
main.go

Renames the Go module to `github.com/elastic/terraform-provider-ec` to
match the correct repository location.
Correct initial commit module name.

mod: Rename to elastic/terraform-provider-ec

---

ec/ecresource/deploymentresource/apmstate/apm_expanders.go
ec/ecresource/deploymentresource/apmstate/apm_expanders_test.go
ec/ecresource/deploymentresource/apmstate/apm_flatteners.go
ec/ecresource/deploymentresource/apmstate/apm_flatteners_test.go
ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_expanders.go
ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_expanders_test.go
ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_flatteners.go
ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_flatteners_test.go
ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_expanders.go
ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_expanders_test.go
ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_flatteners.go
ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_flatteners_test.go
ec/ecresource/deploymentresource/expanders_test.go
ec/ecresource/deploymentresource/kibanastate/kibana_expanders.go
ec/ecresource/deploymentresource/kibanastate/kibana_expanders_test.go
ec/ecresource/deploymentresource/kibanastate/kibana_flatteners.go
ec/ecresource/deploymentresource/kibanastate/kibana_flatteners_test.go
ec/ecresource/deploymentresource/schema_apm.go
ec/ecresource/deploymentresource/schema_elasticsearch.go
ec/ecresource/deploymentresource/schema_enteprise_search.go
ec/ecresource/deploymentresource/schema_kibana.go
ec/ecresource/deploymentresource/testutils.go

Removes the purposeless `display_name` attribute.
resources `display_name` serves no purpose
unit.

ec_deployment: Remove display_name attribute

---

.github/workflows/acceptance.yml
.github/workflows/go.yml

This patch updates to the new version, Go 1.15.x.

go: Update to go 1.15

---

ec/ecdatasource/deploymentdatasource/datasource.go

Refactors the `ec_deployment` datasource to use diagnostics.

ec_deployment: Refactor datasource to use diagnostics

---

CONTRIBUTING.md
README.md
build/Makefile.test

Adds contributing documentation.
Closes: https://github.com/elastic/terraform-provider-ec/issues/59

docs: Contributing documentation

---

ec/acc/deployment_checks_test.go
ec/acc/deployment_destroy_test.go
ec/acc/deployment_sweep_test.go
ec/acc/deployment_traffic_filter_checks_test.go
ec/acc/deployment_traffic_filter_destroy_test.go
ec/acc/deployment_traffic_filter_sweep_test.go
ec/acc/sweep_test.go
ec/ecresource/deploymentresource/flatteners_test.go
ec/ecresource/deploymentresource/resource.go
ec/ecresource/deploymentresource/schema.go
ec/ecresource/deploymentresource/schema_apm.go
ec/ecresource/deploymentresource/schema_elasticsearch.go
ec/ecresource/deploymentresource/schema_enteprise_search.go
ec/ecresource/deploymentresource/schema_kibana.go
ec/ecresource/trafficfilterassocresource/resource.go
ec/ecresource/trafficfilterassocresource/schema.go
ec/ecresource/trafficfilterassocresource/testutils.go
ec/ecresource/trafficfilterresource/flatteners_test.go
ec/ecresource/trafficfilterresource/resource.go
ec/ecresource/trafficfilterresource/schema.go
ec/ecresource/trafficfilterresource/testutils.go

There are several functions that do not need to be exported.
They are being changed to unexported.

misc: Unexport functions that are meant to be internal

---

ec/acc/datasource_deployment_basic_test.go
go.mod
go.sum

Updates the terraform-plugin-sdk dependency to v2.0.4

dependencies: Update terraform-plugin-sdk to v2.0.4

---

build/Makefile.dev

Adds make targets to add or remove a fake SDK dependency.
by running `make fake-sdk` and `make remove-fake-sdk`

misc: Add fake-sdk and remove-fake-sdk make targets

---

docs/data-sources/ec_deployments.md

In order to improve our UX this PR documents all available statuses
for the `status` field in each resource kind.
UX

ec_deployments: Document all available statuses

---

examples/deployment_ec2_instance/README.md
examples/deployment_ec2_instance/aws_ec2.tf
examples/deployment_ec2_instance/elastic_deployment.tf
examples/deployment_ec2_instance/provider.tf
examples/deployment_ec2_instance/variables.tf

Showing a simple example of using the ec_deployment provider in conjunction with the AWS provider
Provide more documentation and examples for customers

example: using the ec_provider in conjunction with the aws provider

---

docs/resources/ec_deployment_traffic_filter_association.md

#78
The output was tested with https://registry.terraform.io/tools/doc-preview and looks OK.
The text was reviewed against the [Elastic writing style guide](https://brand.elastic.co/302f66895/p/194a3b-writing-style-guide) and [Terraform guidelines](https://www.terraform.io/docs/registry/providers/docs.html).

[Terraform] Editing ec_deployment_traffic_filter_association.md

---

docs/index.md

#78
The output was tested with https://registry.terraform.io/tools/doc-preview and looks OK.
The text was reviewed against the [Elastic writing style guide](https://brand.elastic.co/302f66895/p/194a3b-writing-style-guide) and [Terraform guidelines](https://www.terraform.io/docs/registry/providers/docs.html).

[Terraform] Editing index.md

---

docs/data-sources/ec_deployment.md

[Terraform] Editing data-sources/ec_deployment.md

---

docs/data-sources/ec_stack.md

#78
- Capitalize the word "stack" only in combination with Elastic
- EC (SaaS) => Elastic Cloud ESS?
- In the Attribute Reference, double check my suggestions for: 
* `accessible` - To have this version accessible/not accessible by the calling user. This is only relevant for Elastic Cloud ESS, not for ECE.
* `min_upgradable_from` - The minimum stack version recommended.
* `upgradable_to` - The stack version you can upgrade to.
* `allowlisted` - To include/not include this version in the `allowlist`. This is only relevant for Elastic Cloud ESS, not for ECE.

[Terraform]  Editing data-sources/ec_stack.md

---

docs/resources/ec_deployment_traffic_filter.md

#78
The output was tested with https://registry.terraform.io/tools/doc-preview and looks OK.
The text was reviewed against the [Elastic writing style guide](https://brand.elastic.co/302f66895/p/194a3b-writing-style-guide) and [Terraform guidelines](https://www.terraform.io/docs/registry/providers/docs.html).

[Terraform] Editing ec_deployment_traffic_filter.md

---

examples/deployment_ccs/README.md

This PR proposes some editing suggestions for the main `examples/deployment_ccs/README.md`
Relates to #183.

[Terraform] Editing examples/deployment_ccs/README.md

---

examples/README.md

This PR proposes some editing suggestions for the main `examples/README.md`.
Relates to #183.

[Terraform] Editing examples/README.md

---

examples/deployment/README.md

This PR proposes some editing suggestions for  `examples/deployment/README.md`.
Relates to #183.

[Terraform] Editing examples/deployment/README.md

---

examples/deployment_ccs/README.md
examples/deployment_with_init/README.md

This PR proposes some editing suggestions for the main `examples/deployment_with_init`
Relates to #183.

[Terraform] Editing examples/deployment_with_init

---

docs/resources/ec_deployment.md

Note on support regarding importing deployments with user settings.

ec_deployment: Note on importing with user settings (config)

---

docs-elastic/index.asciidoc
docs/index.asciidoc

This PR adds content for the Terraform provider docs on elastic.co.
Relates to 
* https://github.com/elastic/terraform-provider-ec/issues/145
* https://github.com/elastic/docs/pull/1995
Built locally, looks like this: 
~(Note the double horizontal lines. Need to look into what we need to get rid of one of these.)~ Fixed this with Greg's help.

Add Terraform provider docs content

---

go.mod
go.sum

Updates the `elastic/cloud-sdk-go@fa5926f` to fix the stack list sorting
bug.
Bug-free provider.

mod: Update cloud-sdk-go to fix stack list sort

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/GENERIC_QUESTION.md

Enriches the current issue templates with labels and also adds a new
section for bugs where the used terraform definition when the bug was
found should be provided.
Les back and forth when bugs are reported.

templates: Enrich GitHub templates with labels

---

.ci/pipelines/acceptance.Jenkinsfile
.ci/pipelines/release.Jenkinsfile

Changes the Jenkins worker type to a bigger machine since our jobs seem
to be running into resource contention issues.
Less acceptance test failures.

ci: Use a bigger worker node n1-highcpu-8

---

build/Makefile.release

This patch removes the `-dev` label on the generated `version.go` file.
Release with no `-dev` label in the version.
`make release-no-publish`

release: Correct release version suffixes

---

docs/resources/ec_deployment.md

Quick change to update `ec_deployment.md` documentation to reference the correct value for remote clusters.
🔴 `ignore_unavailable`
🟢 `skip_unavailable`
With `ignore_unavailable = true` my plan fails
```
Error: Unsupported argument
on global_olly_cluster.tf line 26, in resource "ec_deployment" "global_o11y_cluster":
26:       ignore_unavailable    = true
An argument named "ignore_unavailable" is not expected here.
```
Using `skip_unavailable = true` == No errors.

Quick fix to ec_deployment documentation

---

examples/deployment/deployment.tf
examples/deployment/es_settings.yaml
examples/deployment_ccs/deployment.tf
examples/deployment_ec2_instance/provider.tf
examples/deployment_with_init/provider.tf
examples/extension_bundle/extension.tf

- Added a comment to the examples section clarifying why .12.29 is used
- Added an es_settings.yaml file to demonstrate usage of config in elasticsearch block.
run locally

Added es_settings to examples

---

examples/deployment/deployment.tf
examples/deployment_ccs/deployment.tf
examples/deployment_ec2_instance/elastic_deployment.tf
examples/deployment_ec2_instance/variables.tf
examples/deployment_with_init/deployment.tf

Updates all examples to retrieve the latest stack pack version
rather than use a hardcoded version which can go out of date.
Related: #256 
By trying out the example

docs: Update examples to use latest available version

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md

Updates bug issue template to request more information about usage.
Make debugging easier :)

gh issues: Update bug issue template

---

.github/workflows/branch.yml

Adds an auto-branching action when a new tag is pushed.
Auto-branch on `MAJOR.MINOR` when a new tag is pushed..

release: Add auto-branching action

---

README.md
docs/index.md

Updates the main index file to follow a different structure.
I've removed the example usage from the Terraform Registry index since
those are covered in detail in each of the resources.
https://registry.terraform.io/tools/doc-preview

docs: Update registry index file and main readme

---

docs/resources/ec_deployment_extension.md
ec/acc/deployment_extension_basic_test.go
ec/ecresource/extensionresource/resource.go

Adds support to import `ec_deployment_extension` resources.
Support importing the resource which was not implemented.

ec_deployment_extension: Support import

---

docs/resources/ec_deployment.md

Adds a note on our documentation warning about potential problems on
modifying deployments when the Kibana instance is disabled.
Closes #276
Warn about unintended effects of disabling a deployment's Kibana instance.

ec_deployment: Add note on disabling kibana

---

.ci/jobs/elastic+terraform-provider-ec+tag.yml

The complete refspec and path glob was missing.
Releases shouldn't need to be triggered manually.

release: Fix Jenkins release job

---

.changelog/208.txt
.changelog/209.txt
.changelog/216.txt
.changelog/218.txt
.changelog/235.txt
.changelog/238.txt
.changelog/241.txt
.changelog/242.txt
.changelog/244.txt
.changelog/248.txt
.changelog/253.txt
.changelog/264.txt
.changelog/266.txt
Makefile
README.md
ec/version.go
examples/deployment/deployment.tf
examples/deployment_ccs/deployment.tf
examples/deployment_ec2_instance/provider.tf
examples/deployment_with_init/provider.tf
examples/extension_bundle/extension.tf

release: Bump version to 0.2.0

---

.changelog/291.txt
CHANGELOG.md
docs/resources/ec_deployment.md
ec/acc/deployment_dedicated_test.go
ec/acc/testdata/deployment_dedicated_coordinating.tf
ec/acc/testdata/deployment_dedicated_master.tf
ec/ecresource/deploymentresource/elasticsearch_expanders.go
ec/ecresource/deploymentresource/elasticsearch_flatteners.go
ec/ecresource/deploymentresource/expanders_test.go
ec/ecresource/deploymentresource/testdata/template-aws-hot-warm-v2.json
ec/ecresource/deploymentresource/testdata/template-aws-io-optimized-v2.json

Fixes a bug where enabling a dedicated tier for ingest or master with an
API error.
Closes #286 
Unit, manual and acceptance tests.

ec_deployment: Fix dedicated master or ingest tier handling

---

.changelog/296.txt

Adds the missing file to update the changelog with the autoscaling feature.
#296

changelog: Add autoscaling entry

---

.changelog/298.txt
docs/data-sources/ec_deployment.md
docs/resources/ec_deployment.md
ec/acc/datasource_deployment_basic_test.go
ec/acc/deployment_basic_test.go
ec/acc/testdata/datasource_deployment_basic.tf
ec/acc/testdata/deployment_basic.tf
ec/acc/testdata/deployment_basic_settings_config_1.tf
ec/ecdatasource/deploymentdatasource/datasource.go
ec/ecdatasource/deploymentdatasource/datasource_test.go
ec/ecdatasource/deploymentdatasource/schema.go
ec/ecresource/deploymentresource/expanders.go
ec/ecresource/deploymentresource/expanders_test.go
ec/ecresource/deploymentresource/flatteners.go
ec/ecresource/deploymentresource/flatteners_test.go
ec/ecresource/deploymentresource/schema.go
ec/ecresource/deploymentresource/testdata/deployment-aws-io-optimized-extension.json
ec/ecresource/deploymentresource/testdata/deployment-aws-io-optimized-tags.json
ec/ecresource/deploymentresource/testdata/deployment-aws-io-optimized.json
ec/ecresource/deploymentresource/testdata/deployment-azure-io-optimized.json
ec/ecresource/deploymentresource/testdata/deployment-gcp-io-optimized.json
ec/ecresource/deploymentresource/testutil_datastruct.go

Adds support for deployment aliases on both the `ec_deployment` resource
and `ec_deployment` datasource.
Closes #287 
Manual, unit and acceptance tested.

ec_deployment: Add support for deployment aliases

---

.github/workflows/changelog_generation.yml

Updates the command to be run to commit & push.

changelog: Update git commit & push

---

.changelog/296.txt
.changelog/298.txt
.changelog/300.txt
.changelog/308.txt
.changelog/309.txt
.changelog/322.txt
.changelog/324.txt
CHANGELOG.md
Makefile
ec/version.go
examples/deployment/deployment.tf
examples/deployment_ccs/deployment.tf
examples/deployment_ec2_instance/provider.tf
examples/deployment_with_init/provider.tf
examples/extension_bundle/extension.tf

Removes previous changelog entries and bumps the version

Remove changelog entries and bump version

---

.github/workflows/branch.yml
Makefile
build/Makefile.deps
build/Makefile.version

Automates the version update after every release.

release: Add version bump automation

---

.ci/pipelines/acceptance.Jenkinsfile
.ci/pipelines/release.Jenkinsfile
.github/workflows/changelog_generation.yml
.github/workflows/go.yml

Updates the Go version to the latest available version.

go: Update to latest `1.17` version

---

NOTICE

Running `make vendor` updates `NOTICE` file. It seems like it might be outdated..
Same as https://github.com/elastic/ecctl/pull/509

deps: Update NOTICE

---

.github/workflows/changelog_generation.yml
.github/workflows/go.yml
NOTICE

This PR adds a Github Action to commit changed NOTICE file

Add auto-commit of NOTICE file

---

ec/ecresource/deploymentresource/flatteners_test.go

Fixes the broken unit test that made the build fail.
Passing unit tests.

ec_deployment: Fix broken unit test

---

.changelog/364.txt

Adds the missing changelog entry for the change introduced in #364

Add changelog entry for keystore resource

---

README.md

This PR adds a link to the new Terraform provider for Elastic Stack.

Add info about Stack provider to readme

---

docs/resources/ec_deployment.md

Related to https://github.com/elastic/terraform-provider-ec/issues/459
Clarifies that imported resources will not have all available attributes.

Include a note in the import docs mentioning that the credentials will not be available

---

.github/workflows/branch.yml

These were changed in v8. https://github.com/EndBug/add-and-commit/blob/main/CHANGELOG.md#800---2022-01-20

Fixes arguments for add-and-commit

---

CHANGELOG.md

Brings 0.4.1 changelog entries into the master branch.

Bring forward 0.4.1 changelog

---

docs/resources/ec_deployment_extension.md

A slow network may cause timeouts on uploading an extension; suggests
increasing the timeout setting.
Closes #498
- Truth: Uploading an extension is more likely to fail due to the data size.
- Issue: It's not clear (at least for me) what to do for the issue.
- Solution: A note about the potential timeouts in documentation.
#498
I had to spend time to find the right path is not [resource timeout setting](https://www.terraform.io/plugin/sdkv2/resources/retries-and-customizable-timeouts) but [provider's timeout setting](https://registry.terraform.io/providers/elastic/ec/latest/docs#timeout).
Just by the workflow in Github Actions.

doc: Add a note about potential timeouts

---

docs/index.md

Correct the default timeout in documentation according to the change in #128.
Closes #496
In #128, the default timeout was changed to 40 seconds [here](https://github.com/elastic/terraform-provider-ec/pull/128/files#diff-8a99a7c023fb0016302c46546d8bb5ae8bc57df60f6ee46166faf4d536fceff4R57).
This PR makes the doc up to date.
https://github.com/elastic/terraform-provider-ec/issues/496
Just for better consistency between code and doc.
Just by the workflow in Github Actions.

doc: Correct documented default timeout to 40s

---

docs/resources/ec_deployment.md

Improve an example with autoscale

---

build/Makefile.deps
build/Makefile.lint

Golint is [deprecated](https://github.com/golang/lint/commit/6edffad5e6160f5949cdefc81710b2706fbcd4f6) and doesn't support generic code.

Golint is deprecated

---

.changelog/507.txt
.changelog/533.txt
.changelog/534.txt
.changelog/536.txt
.changelog/546.txt
.changelog/548.txt
CHANGELOG.md

Post 0.5.0 version bump

---

ec/ecresource/deploymentresource/schema_elasticsearch.go

We start using the strategy setting and we realized that the plan does not contain the setting in most of the cases, after checking what happens the cause is the DiffSuppressFunc, it removes the changes in most of the cases. Due to the setting being a transient setting and probably not extended used (probably us only) removing the DiffSuppressFunc does not have any impact.
https://github.com/elastic/terraform-provider-ec/pull/507
* We create a cluster with the setting and we try to make some Docker image changes with the strategy setting configured to restart all nodes at the same time. Then we verify the plan does not have the proper configuration.
* Since then we are using a SNAPSHOT (with this change ) version of the Elastic Terraform provider to update our clusters and work as …

fix: remove strategy DiffSuppressFunc

---

CHANGELOG.md
ec/ecdatasource/privatelinkdatasource/regionPrivateLinkMap.json

Fix incorrect private link data for Azure eastus

---

.changelog/625.txt
docs/resources/ec_snapshot_repository.md
ec/acc/deployment_template_migration_test.go
ec/acc/testdata/deployment_basic_defaults_hw_2.tf
ec/ecresource/deploymentresource/apm/v2/apm_payload.go
ec/ecresource/deploymentresource/apm/v2/apm_payload_test.go
ec/ecresource/deploymentresource/deployment/v2/deployment_create_payload.go
ec/ecresource/deploymentresource/deployment/v2/deployment_update_payload.go
ec/ecresource/deploymentresource/deployment/v2/deployment_update_payload_test.go
ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_payload.go
ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_payload_test.go
ec/ecresource/deploymentresource/elasticsearch/v2/node_roles.go
ec/ecresource/deploymentresource/enterprisesearch/v2/enterprise_search_payload.go
ec/ecresource/deploymentresource/enterprisesearch/v2/enterprise_search_payload_test.go
ec/ecresource/deploymentresource/enterprisesearch/v2/schema.go
ec/ecresource/deploymentresource/integrationsserver/v2/integrations_server_payload.go
ec/ecresource/deploymentresource/integrationsserver/v2/integrations_server_payload_test.go
ec/ecresource/deploymentresource/integrationsserver/v2/schema.go
ec/ecresource/deploymentresource/kibana/v2/kibana_payload.go
ec/ecresource/deploymentresource/kibana/v2/kibana_payload_test.go
ec/ecresource/deploymentresource/kibana/v2/schema.go
ec/ecresource/deploymentresource/testutil/testutil_func.go
ec/internal/planmodifier/attribute_changed.go
ec/internal/planmodifier/use_state_unless_template_changed.go

Reintroduce the changes from https://github.com/elastic/terraform-provider-ec/pull/547 into the provider. 
Fixes https://github.com/elastic/terraform-provider-ec/issues/622
Manually, acceptance tests

Utilise the migrate template API when applying changes to the deployment template id

---

ec/acc/testdata/deployment_upgrade_retry_1.tf
ec/acc/testdata/deployment_upgrade_retry_2.tf

The failed upgrade test, it haunts my dreams. Adorned with badly constructed regexes and failed builds. 
Surprisingly by running the acceptance test itself. Shocking I know.

Fix failed upgrade acceptance test version regex

---

docs/index.md
templates/index.md.tmpl

Related to https://github.com/elastic/terraform-provider-ec/issues/618
Not all documented outputs are available in TF < 1.2.7. I believe this is related to https://github.com/hashicorp/terraform/pull/31532 but haven't actually confirmed that. Documenting the limitation for future users.

Add minimum Terraform CLI requirements into the docs

---

.changelog/640.txt
docs/resources/deployment.md
ec/ecresource/deploymentresource/integrationsserver/v2/integrations_server_payload.go
ec/ecresource/deploymentresource/integrationsserver/v2/integrations_server_read.go
ec/ecresource/deploymentresource/integrationsserver/v2/integrations_server_read_test.go
ec/ecresource/deploymentresource/integrationsserver/v2/schema.go

Explicitly captures the Fleet and APM endpoints within an Integrations Server resource. 
Fixes https://github.com/elastic/terraform-provider-ec/issues/605
Unit, manual testing

Fleet endpoints

---

.changelog/690.txt
ec/ecresource/deploymentresource/create.go

Fixes https://github.com/elastic/terraform-provider-ec/issues/569
Manually, I can't see a way to test this via an acceptance test.

Set the deployment id in state as soon as it's available to avoid unmanaged resources

---

docs/data-sources/aws_privatelink_endpoint.md
examples/data-sources/ec_aws_privatelink_endpoint/data-source.tf

Fixes up copy-pasta
Fixes https://github.com/elastic/terraform-provider-ec/issues/644

Fixup aws_privatelink_endpoint docs

---

docs/resources/deployment.md
templates/resources/deployment.md.tmpl

Fix typo in deployment.md. Change c back to ascii character.

Fix typo in deployment.md

---

.changelog/719.txt
ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_payload.go
ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_payload_test.go
ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_snapshot.go
ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_snapshot_source.go

Fix segfaults during Create/Update for `ec_deployment`
- when `elasticsearch` attribute contains both `strategy` and `snapshot_source`;
- when `elasticsearch` defines `snapshot` with `repository` that doesn't contain `reference`.
Closes: #715

Fix segfaults during Create/Update for `ec_deployment`.

---

.buildkite/release.yml
catalog-info.yaml

Add an empty Buildkite pipeline for releasing the provider
Supporting the migration from Jenkins to Buildkite

Add Buildkite release pipeline

---

ec/ecresource/deploymentresource/read.go

Fix typo in message when deployment get error

Fix typo in error message

---

ec/acc/deployment_docker_image_override_test.go

The test is failing in both Jenkins and Buildkite and as a result the acceptance test suite is completely ignored. I'd suggest skipping the test (fix to be tracked [here](https://github.com/elastic/terraform-provider-ec/issues/746)) until it can be fixed to get the acceptance suite back up and running.

Disable failing test until further investigation

---

.buildkite/hooks/pre-command
.buildkite/release.sh

This change, related to https://github.com/elastic/ci/pull/2506 updates the release script to read the PGP keys from a more secured location shared with less folks. The GPG key information is now in a secured shared location accessible only to members of the GH group `terraform-providers-admins` and to the CI pipelines of this repository and terraform-provider-elasticstack.
be more secured, reduce blast radius in case of security issue
I ran the release pipeline in "-no-publish" mode

Secured release pipeline

---

catalog-info.yaml

Build PR for forks

---

.buildkite/pull-requests.json
catalog-info.yaml

Add BK bot config

---

catalog-info.yaml

Enable building PRs so Buildkite bot works properly

---

docs/resources/deployment.md

This PR makes a small update to the docs related to deployment template/hardware migrations.

Update template migration docs

---

README.md
docs/index.md
templates/index.md.tmpl

To address https://github.com/elastic/terraform-provider-ec/issues/784, I would like to add a generic version guidance to recommend users to always use the latest version of both the Terraform ec provider and Terraform CLI, to avoid hitting known issues and to get better user experience.
It's a doc PR and not a code change.

Add a generic version guidance

---

.changelog/823.txt
ec/ecdatasource/privatelinkdatasource/regionPrivateLinkMap.json

Does what it says on the tin
Fixes https://github.com/elastic/terraform-provider-ec/issues/822

Update PSC data source data.

---

.github/workflows/branch.yml

In workflow, `set-output` command is deprecated and will be disabled soon. For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
https://github.com/elastic/terraform-provider-ec/blob/6e18a059218406fc56b8a0d93076205b01137e1e/.github/workflows/branch.yml#L35
Fixes #829

Replace deprecated command with environment file

---

docs/resources/deployment_traffic_filter.md
templates/resources/deployment_traffic_filter.md.tmpl

Fix broken markdown formatting.
There should be a space after the `###`.
here. https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/deployment_traffic_filter#example-usage
None.
I was just reading the documentation for using PSC when I noticed a formatting error.
Documentation fixes only.

Fix broken markdown formatting
