README.md, docs/index.md, ec/acc/acc_prereq.go, ec/acc/sweep_test.go, ec/provider.go
`ECE_API_KEY` is the only recommended format in the Elastic Cloud [documentation](https://www.elastic.co/guide/en/cloud/current/ec-api-authentication.html).
It makes sense to only accept that format in order to avoid confusions with our users.
UX
By running both unit and acceptance tests
=> misc: Only accept EC_API_KEY as the API key environment variable

ec/acc/deployment_test.go, ec/acc/testdata/deployment_enterprise_search.tf, ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_expanders.go, ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_expanders_test.go, ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_flatteners.go, ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_flatteners_test.go, ec/ecresource/deploymentresource/expanders.go, ec/ecresource/deploymentresource/expanders_test.go, ec/ecresource/deploymentresource/flatteners.go, ec/ecresource/deploymentresource/flatteners_test.go, ec/ecresource/deploymentresource/schema.go, ec/ecresource/deploymentresource/testutils.go, examples/deployment_enterprise_search/README.md, examples/deployment_enterprise_search/deployment.tf, go.sum
Adds EnterpriseSearch as a manageable resource type.
Closes: #13 
- By running acceptance tests:
```console
$ make testacc
-> Formatting Go files...
-> Formatting Terraform documentation blocks...
-> Done.
=== RUN   TestAccDeployment_basic
=== PAUSE TestAccDeployment_basic
=== RUN   TestAccDeployment_appsearch
=== PAUSE TestAccDeployment_appsearch
=== RUN   TestAccDeployment_enterpriseSearch
=== PAUSE TestAccDeployment_enterpriseSearch
=== CONT  TestAccDeployment_basic
=== CONT  TestAccDeployment_enterpriseSearch
=== CONT  TestAccDeployment_appsearch
--- PASS: TestAccDeployment_appsearch (251.77s)
--- PASS: TestAccDeployment_enterpriseSearch (380.84s)
--- PASS: TestAccDeployment_basic (444.24s)
PASS
ok …
```
=> deploymentresource: Add support for EnterpriseSearch resource type

.github/workflows/acceptance.yml, .github/workflows/go.yml
Adds the acceptance tests `make testacc` run to the workflow run in all
the commits and branches, but omitting the pull_request trigger due to
the GitHub Actions limitations on forks.
Run the acceptance tests in tests in GH Actions.
=> ci: Add Acceptance tests to GitHub action workflow

ec/acc/deployment_basic_test.go, ec/ecresource/deploymentresource/resource.go
This change adds the basic ID passthrough importer which allows users to
import existing deployments.
Providing the ability to import deployments but secret fields will be
missing:
* `elasticsearch_username`
* `elasticsearch_password`
Resolves #9 
Importing an existing deployment and adding the `import` test case.
=> ec_deployment: Support terraform import

examples/deployment/outputs.tf
This patch adds an example `outputs.tf` file to the examples,
which returns the credentials for connecting to the cluster.
=> Add outputs to "examples/deployment"

ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_expanders.go, ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_expanders_test.go, ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_flatteners.go, ec/ecresource/deploymentresource/enterprisesearchstate/enterprise_search_flatteners_test.go, ec/ecresource/deploymentresource/schema_enteprise_search.go
Deletes `secret_session_key` from the `enterprise_search` schema and all
the flattening / expanding from / to state.
Delete setting which isn't useful.
=> ec_deployment:Delete Enterprise Search session_key

ec/ecdatasource/deploymentdatasource/schema_elasticsearch.go, ec/ecresource/deploymentresource/elasticsearchstate/elasticsearch_expanders.go, ec/ecresource/deploymentresource/schema_elasticsearch.go
Removes the unimplemented `snapshot_settings` attribute from the source
code since Snapshot settings shouldn't be managed in `ec_deployment`.
Remove unused code and attributes which aren't usable.
=> ec_deployment: Remove snapshot_settings attribute

build/Makefile.format, build/Makefile.lint, build/Makefile.test
Adds `terraform fmt` to both `lint` and `format` makefile targets.
`format`: will rewrite the files, while `lint` will return with an error
when the files aren't formatted according to `terraform fmt`.
Have `terraform fmt` run the checks in the CI.
=> ci: Add terraform fmt to lint and format targets

.ci/Makefile, .ci/jobs/elastic+terraform-provider-ec+pull-request.yml, .ci/pipelines/acceptance.Jenkinsfile, .github/workflows/acceptance.yml
Fixes a few issues with the committed pipeline and build configurations.
First, The path used for the secret wasn't readable by the vault role
configured in the `devops-ci`, furthermore that key contained more
credentials in the secret path. Instead of using the initial path, a new
secret has been created in the Vault server with only the apikey
credentials, in a path accessible by the vault role.
Second, fixes the docker `golang` docker image to  use the tag  `1.15`.
Last, it changes the `acceptance.yml` github action to only run on the
push operation in the master branch. This is temporary and until the
master build in Jenkins is fixed (Currently not triggered).
Part of #58
=> ci: Fix broken acceptance build pipeline

docs/datasources/ec_stack.md, ec/acc/datasource_stack_test.go, ec/acc/testdata/datasource_stack_latest.tf, ec/acc/testdata/datasource_stack_regex.tf, ec/ecdatasource/stackdatasource/datasource.go, ec/ecdatasource/stackdatasource/datasource_test.go, ec/ecdatasource/stackdatasource/schema.go, ec/ecdatasource/stackdatasource/state/flatteners_apm.go, ec/ecdatasource/stackdatasource/state/flatteners_apm_test.go, ec/ecdatasource/stackdatasource/state/flatteners_elasticsearch.go, ec/ecdatasource/stackdatasource/state/flatteners_elasticsearch_test.go, ec/ecdatasource/stackdatasource/state/flatteners_enterprise_search.go, ec/ecdatasource/stackdatasource/state/flatteners_enterprise_search_test.go, ec/ecdatasource/stackdatasource/state/flatteners_kibana.go, ec/ecdatasource/stackdatasource/state/flatteners_kibana_test.go, ec/provider.go, go.sum
Adds a new data source which allows the terraform provider users to get
information about a specific stack version by using a `version_regex`.
The `version_regex` field also accepts a `"latest"` string as a value
which will cause the data source to obtain the latest available stack
version and return it, best used with `lock`.
There's quite a lot of fields contained in the Stack models and this PR
implements most of the fields which might not even be useful in the long
run, but can be useful to browse around what capabilities are in a stack
version.
```hcl
data "ec_stack" "latest" {
version_regex = "latest"
region        = "us-east-1"
lock          = true
}
```
```hcl
data "ec_stack" "latest" {
version_regex = "7.9.?"
region        = "us-east-1"
}
```
Fixes #66 
```console
$ make testacc …
```
=> ec_stack: Add Data Source

ec/acc/deployment_traffic_filter_checks_test.go, ec/acc/deployment_traffic_filter_destroy_test.go, ec/acc/deployment_traffic_filter_sweep_test.go
This patch refactors traffic filter tests to use trafficfilterapi instead
of the APIs from the generated swagger code.
```console
=== RUN   TestAccDeploymentTrafficFilterAssociation_basic
=== PAUSE TestAccDeploymentTrafficFilterAssociation_basic
=== RUN   TestAccDeploymentTrafficFilter_basic
=== PAUSE TestAccDeploymentTrafficFilter_basic
=== CONT  TestAccDeploymentTrafficFilterAssociation_basic
=== CONT  TestAccDeploymentTrafficFilter_basic
--- PASS: TestAccDeploymentTrafficFilter_basic (66.97s)
--- PASS: TestAccDeploymentTrafficFilterAssociation_basic (210.40s)
PASS
ok  	github.com/elastic/terraform-provider-ec/ec/acc	211.955s
```
=> acceptance: Refactor traffic filter tests to use trafficfilterapi

ec/acc/datasource_deployment_basic_test.go, ec/acc/testdata/datasource_deployment_basic.tf
Follow up PR for https://github.com/elastic/terraform-provider-ec/pull/91 which adds acceptance tests.
```console
=== RUN   TestAccDatasourceDeployment_basic
=== PAUSE TestAccDatasourceDeployment_basic
=== CONT  TestAccDatasourceDeployment_basic
--- PASS: TestAccDatasourceDeployment_basic (443.13s)
PASS
ok  	github.com/elastic/terraform-provider-ec/ec/acc	444.707s
```
=> acceptance: Update ec_deployment datasource test to include traffic filter

.ci/jobs/elastic+terraform-provider-ec+pull-request.yml
Sets `cancel-builds-on-update` to `false` on the job definition to avoid
leaving dangling resources when builds are cancelled.
Avoid leaving costly dangling resources.
=> ci: Do not cancel builds on commit push

ec/ecdatasource/deploymentdatasource/datasource_test.go, ec/ecdatasource/deploymentsdatasource/datasource_test.go, ec/ecdatasource/deploymentsdatasource/expanders_test.go, ec/ecdatasource/stackdatasource/datasource_test.go, ec/ecresource/deploymentresource/expanders_test.go, ec/ecresource/deploymentresource/flatteners_test.go, ec/ecresource/deploymentresource/testutils.go, ec/ecresource/deploymentresource/update_test.go, ec/ecresource/trafficfilterassocresource/expanders_test.go, ec/ecresource/trafficfilterassocresource/flatteners_test.go, ec/ecresource/trafficfilterresource/expanders_test.go, ec/ecresource/trafficfilterresource/flatteners_test.go, ec/ecresource/trafficfilterresource/testutils.go, ec/internal/util/testutils.go
The `NewResourceData` function and its corresponding `ResDataParams`
struct were being copy pasted to every package. This has won the function
it's place in the `util` package to be reused in all tests.
`make unit`
=> test: Move NewResourceData function to utility package

ec/acc/deployment_hotwarm_test.go, ec/acc/testdata/deployment_hotwarm_1.tf, ec/acc/testdata/deployment_hotwarm_2.tf, ec/ecresource/deploymentresource/elasticsearch_expanders.go, ec/ecresource/deploymentresource/elasticsearch_expanders_test.go
This patch fixes a bug where the topology.ElasticsearchConfig setting
was being overridden when some topology settings were being set, since
there was a reassignment back to `elem.Elasticsearch`.
The change now takes in the existing ElasticsearchConfig and sets what
needs to be overwritten instead of creating a new object and reassigning
the result back to the property, which was creating this issue.
It is unlikely that the same situation occurs in the other deployment
resources, but it might be good to change the other resources functions
use the same signature.
Closes #111 
Manually, and added an acceptance test case too.
=> ec_resource: Fix overwritten elasticsearch config

Makefile, ec/version.go, gen/gen.go
Adds a `-dev` suffix  to the committed version Makefile, also modifying
the Go generator to enclose the variable in double quotes which was done
externally before.
Avoid categorizing outgoing API calls to a released version when it might not.
=> version: Add "-dev" suffix to committed version

ec/acc/datasource_deployment_basic_test.go, ec/acc/testdata/datasource_deployment_basic.tf
`name_prefix` is now unique enough, so that if there happen to be any 
dangling resources the tests will consistently pass.
Closes: https://github.com/elastic/terraform-provider-ec/issues/116
By running the tests while another deployment with the `test_acc_`
prefix existed.
```console
$ make testacc TEST_NAME=TestAccDatasourceDeployment_basic
=== RUN   TestAccDatasourceDeployment_basic
=== PAUSE TestAccDatasourceDeployment_basic
=== CONT  TestAccDatasourceDeployment_basic
--- PASS: TestAccDatasourceDeployment_basic (391.60s)
PASS
ok  	github.com/elastic/terraform-provider-ec/ec/acc	392.717s
```
=> acceptance: Improve ec_deployments datasource query test

docs/index.md, ec/provider.go, ec/provider_config.go, ec/provider_config_test.go
This patch has two kinds of changes, user facing and a small refactoring
to allow the creation flow of `api.Config` to be unit tested.
User facing:
- By default, the Authorization header contents will now be redacted.
- Adds a new `verbose_credentials` boolean which allows users to dump
the raw Authorization header in the log file.
- Adds a new `verbose_file` string which allows users to control the
file where the request log is written to (defaults to `request.log`).
- Fixes a bug where the default timeout wasn't properly set to `1m`.
- Updates the `index.md` file.
Refactoring:
- Moves the provider schema to its own function to make easy to create
*schema.ResourceData instances from it.
- `verboseSettings` wasn't returning an error on `os.Create` which just
failed silently, this wasn't …
=> config: Add verbose_ credentials and file setting

ec/provider.go, ec/provider_config_test.go
Reduce the timeout to `40s` from `1m` since any potential client network
instability needn't take 1m to resolve and is likely that a retry might
make the request succeed when retried.
Still `40s` is a reasonable timeout time for most requests.
Retries should take care of timed out requests and `1m` timeout seems excessive for the the timeouts that are most likely to be cause by client network issues.
running `make testacc`
=> config: Reduce timeout to 40s

docs/resources/ec_deployment.md
Adds a warning note on the `ec_deployment` resource about importing pre-
Slider deployments.
Part of #10
Action item from #125 
Doesn't make them work, but at least there's a note about it
=> docs: Add note on importing legacy deployments

.github/CODEOWNERS
Changes `CODEOWNERS` file to include cloud writers as co-owners of
the `docs/` directory.
=> misc: Documentation ownership for cloud writers

build/Makefile.test, ec/acc/acc_prereq.go, ec/acc/datasource_deployment_basic_test.go, ec/acc/datasource_stack_test.go, ec/acc/deployment_basic_defaults_test.go, ec/acc/deployment_basic_test.go, ec/acc/deployment_ccs_test.go, ec/acc/deployment_checks_test.go, ec/acc/deployment_config_test.go, ec/acc/deployment_destroy_test.go, ec/acc/deployment_hotwarm_test.go, ec/acc/deployment_sweep_test.go, ec/acc/deployment_traffic_filter_association_test.go, ec/acc/deployment_traffic_filter_checks_test.go, ec/acc/deployment_traffic_filter_destroy_test.go, ec/acc/deployment_traffic_filter_sweep_test.go, ec/acc/deployment_traffic_filter_test.go, ec/acc/sweep_test.go, ec/ecresource/deploymentresource/resource.go
Removes the acceptance build tag and instead adds a new function which
calls `t.Skip()` when a function with a `*testing.T` as the first arg
requires external HTTP access, in which case it is skipped, to trigger
this behavior any tests which fall into that category should call
`requiresAPIConn` at the beginning of the function to ensure that we're
not incurring any errors when calling `newAPI()`.
`acceptance` build tag introduced in #121
This was bothering me since writing tests was becoming quite cumbersome
due to the go build avoidance on the `+build acceptance` tag.
=> acceptance: Remove acceptance build tag

build/Makefile.test, ec/ecresource/trafficfilterassocresource/resource.go, ec/ecresource/trafficfilterresource/resource.go, go.mod, go.sum
This change sets the maximum number of tests allowed to run to default
to `4` unless `TEST_ACC_PARALLEL` is set to a different value by the
user.
This avoids resource starvation on test running machines.
Additionally, updates the `cloud-sdk-go` dependency to include the last
change on the client timeouts.
running `make acceptance` while connected to a slow network.
=> acceptance: Set parallel tests to 4

docs/data-sources/ec_deployment.md, docs/resources/ec_deployment.md, ec/acc/datasource_deployment_basic_test.go, ec/acc/testdata/datasource_deployment_basic.tf, ec/ecdatasource/deploymentdatasource/datasource.go, ec/ecdatasource/deploymentdatasource/datasource_test.go, ec/ecdatasource/deploymentdatasource/flatteners_observability.go, ec/ecdatasource/deploymentdatasource/flatteners_observability_test.go, ec/ecdatasource/deploymentdatasource/schema.go
The new observability block is now read by the `ec_deployment`
datasource as well.
Closes: https://github.com/elastic/terraform-provider-ec/issues/148
Manually and through acceptance tests.
=> ec_deployment: Add observability settings to datasource

build/Makefile.test
Updates the `TEST_ACC_PARALLEL` to `6` to help speed up the acceptance
tests.
Faster acceptance test runs, but still stable.
=> testacc: Update default -parallel from 4 to 6

ec/acc/deployment_config_test.go, ec/ecresource/deploymentresource/expanders.go, ec/ecresource/deploymentresource/expanders_test.go
As the bug with the `GET deployments/template/{template_id}` endpoint
has been fixed, we no longer need to use the `AsList` field when calling it.
Stay up to date!
With acc tests
=> ec_deployment: Stop making use of AsList field in deployment template get calls

docs/resources/ec_deployment.md, ec/ecresource/deploymentresource/elasticsearch_expanders.go, ec/ecresource/deploymentresource/import.go, ec/ecresource/deploymentresource/import_test.go, ec/ecresource/deploymentresource/resource.go, go.mod, go.sum
Adds a custom import function limiting the imported version to `6.6.0`
or higher. Additionally, always removes the Elasticsearch curation
settings if found.
Superseeds #178 and #167 
Manually trying to import a `2.4.5` deployment:
```console
$ terraform import ec_deployment.example_minimal 18xxxxx
ec_deployment.example_minimal: Importing from ID "18xxxxx"...
Error: invalid deployment version "2.4.5": minimum supported version is "6.6.0"
```
=> ec_deployment: Limit version to 6.6.0 or higher

examples/README.md, examples/deployment/README.md, examples/deployment_ccs/README.md
Just a doco change, noticed when running through examples.
Are these examples supposed to spin up enterprise search as well? Found it confusing when I hit the UI and saw lots of "Getting started with Enterprise Search" text.
=> Terraform init is required before apply

ec/acc/datasource_deployment_basic_test.go, ec/acc/testdata/datasource_deployment_basic.tf, ec/ecdatasource/deploymentsdatasource/datasource.go, ec/ecdatasource/deploymentsdatasource/datasource_test.go
Changes the ID setting strategy for the deployments data source to use
a hash of the search response returned from the API, this causes the
data source ID to not be re-generated every time terraform is run. Also
adds `depends_on` to the tf acceptance tests on that data source to help
the test succeed more consistently.
Better acceptance test passing consistency
=> data ec_deployments: Change ID generation to hashing

.github/workflows/release.yml, .gitignore, .goreleaser.yml, Makefile, README.md, build/Makefile.deps, build/Makefile.release, docs/index.md, ec/acc/testdata/deployment_basic_defaults_3.tf, ec/version.go, examples/deployment/deployment.tf, examples/deployment_ccs/deployment.tf, examples/deployment_ec2_instance/provider.tf, examples/deployment_with_init/provider.tf
Adds the goreleaser config and release github action for pushes of `v*`
tags. Adds three new targets: `tag`, `snapshot` and `release`.
The `release` target has been added as a fallback to perform a manual
release in case the GitHub action fails.
Last, it sets the version to `v0.1.0-beta` as agreed with the team.
Part of #44
=> release: Add goreleaser config and github action

docs-elastic/page_header.html
This PR adds a beta header into the v0.1.0-beta docs similar to what we have done in the past for other Cloud products, such as ecctl:
=> Add beta header to the Elastic docs

.ci/.env, .ci/Makefile, .ci/jobs/elastic+terraform-provider-ec+tag.yml, .ci/pipelines/release.Jenkinsfile, .gitignore, build/Makefile.release
Adds a new Jenkins job which should be triggered every time a `v*`  tag
is pushed to the repository.
The job will import the GPG private key, export the required environment
variables and run the `goreleaser` binary to trigger a new release. The
GPG key passphrase will be cached within GPG so `goreleaser` can sign
the release without interactively asking for the passphrase.
Part of #201 
Manually in a docker container:
```
$ make -C .ci .gpg_private .gpg_passphrase .github_token .gpg_fingerprint
$ docker run -ti --rm -v $(pwd):/go/src/github.com/elastic/terraform-provider-ec -w /go/src/github.com/elastic/terraform-provider-ec golang:1.15 bash
$ make vendor
$ make -C .ci import-gpg-key
$ . .ci/.env; make -C .ci cache-gpg-passphrase; make release-no-publish
```
=> release: Add Jenkins release job and file

docs/index.md
This commit addresses 
* the erroneous reference of `insecure`, where `timeout` was intended
* spacing that renders as `&nbsp;`, in favour of space (UTF8 0x20)
Visual inspection in a GH markup editor.
=> Fix in timeout option documentation & markup docs

ec/acc/deployment_sweep_test.go, ec/acc/deployment_sweep_test_test.go
Changes the deployment sweep logic to be time based, deleting all the
deployments that are 1h or older since their last change.
The change will remove any deployments found in the account with the
`terraform_acc_` prefix, without checking the status of any of the
deployment resources.
This results in a proper cleanup of the dev account since the account
had a lot of dangling resources which were costing costing us a few $.
Being able to run `make sweep` non disruptively in a nightly basis.
Running `make sweep` without disrupting ongoing acceptance tests.
=> testacc: Sweep all existing 1h+ old deployments

.goreleaser.yml, build/Makefile.release
Fixes the `make tag` target include a `v` prefix on the tag that is
pushed to GitHub. Additionally, explicitly specifies that the repository
is `elastic/terraform-provider-ec`.
By releasing the `v0.1.0-beta` version.
=> release: Amend make tag target to use a v prefix

build/Makefile.test
Limits the maximum concurrent acceptance tests to `4` by default.
Part of #210 
Reduce the CI load and reducing the amount of capacity used for tests concurrently.
`make testacc`.
=> testacc: limit maximum concurrent tests to 4

docs/resources/ec_deployment.md, ec/acc/deployment_basic_tags_test.go, ec/acc/testdata/deployment_basic_tags_1.tf, ec/acc/testdata/deployment_basic_tags_2.tf, ec/acc/testdata/deployment_basic_tags_3.tf, ec/acc/testdata/deployment_basic_tags_4.tf, ec/ecresource/deploymentresource/expanders.go, ec/ecresource/deploymentresource/expanders_test.go, ec/ecresource/deploymentresource/flatteners.go, ec/ecresource/deploymentresource/flatteners_test.go, ec/ecresource/deploymentresource/schema.go, ec/ecresource/deploymentresource/testdata/deployment-aws-io-optimized-tags.json, go.sum
Adds a new key value map `tags` to the `ec_deployment` resource.
```hcl
resource "ec_deployment" "with_tags" {
name = "my_example_deployment"
region                 = "us-east-1"
version                = "7.9.2"
deployment_template_id = "aws-io-optimized-v2"
elasticsearch {}
tags = {
owner     = "elastic cloud"
component = "search"
}
}
```
Closes #213
Manually and running the acceptance tests.
```console
$ make testacc TEST_NAME=TestAccDeployment_basic_tags
=== RUN   TestAccDeployment_basic_tags
=== PAUSE TestAccDeployment_basic_tags
=== CONT  TestAccDeployment_basic_tags
--- PASS: TestAccDeployment_basic_tags (213.88s)
PASS
ok  	github.com/elastic/terraform-provider-ec/ec/acc	214.236s
```
=> ec_deployment: Add tags key value map

ec/acc/deployment_traffic_filter_test.go, ec/acc/testdata/deployment_traffic_filter_basic_update_large.tf, ec/ecresource/trafficfilterresource/expanders.go, ec/ecresource/trafficfilterresource/expanders_test.go, ec/ecresource/trafficfilterresource/flatteners.go, ec/ecresource/trafficfilterresource/flatteners_test.go, ec/ecresource/trafficfilterresource/schema.go, ec/ecresource/trafficfilterresource/schema_test.go
Fixes a bug where multiple having a traffic filter with a few rules will
cause an infinite diff loop by changing the field from a List to a Set.
This consistently hashes the list using the same algorithm, which does
not happen when the field is of `schema.TypeList`.
Also adds a custom set hashing function for the traffic rules set, using
the source and optional description if found as hashing keys.
Last, changes the assertions to use `TestCheckTypeSetElemNestedAttrs` in
the acceptance tests, asserting the rule values without the position.
Closes #203
Unit and acceptance tested, also tried with an example locally.
=> ec_traffic_filter: Fix rule ordering bug

build/Makefile.lint
Fixes a bug where the `lint` target didn't have the `-check` flag set,
which caused the target to return with status code 0 even when there are
files that aren't formatted according to `terraform fmt`.
Proper validation of terraform formatted files in our CI.
`make lint`
=> lint: Fix terraform fmt to return exit code > 0

.ci/pipelines/acceptance.Jenkinsfile, CONTRIBUTING.md, build/Makefile.test, ec/acc/deployment_sweep_test.go, ec/acc/deployment_traffic_filter_sweep_test.go
This patch adds a new target `sweep-ci` which sweeps `ec_deployments`
resources that have had their last change > 1h ago, it doesn't target
other resource sweepers as it makes use of the flag `-sweep-name`.
`make sweep-ci` will be called on the cleanup step which is always run
ensuring that we don't periodically leave costly dangling resources as
a result of our acceptance tests.
The sweeper for `ec_deployment` has been renamed to `ec_deployments` to
avoid matching other resources prefixed with `ec_deployments` since the
terraform sweep filter uses the Go func `strings.Contains`. A debug log
line has also been added to each deployment that is swept as a trail.
Last, the `CONTRIBUTING.md` file has been edited to add more information
about the sweepers.
Closes #207
No more dangling …
=> ci: Clean acc dangling deployments on cleanup step

ec/acc/deployment_destroy_test.go
Fixes the post-destroy check for the `ec_deployment` resource to only
error out when any of the deployments resources is still running and not
when the deployment is found on the backing API since it'll always be
there in ESS.
Less acceptance test failures
=> acc: fix ec_deployment post-destroy check

ec/acc/datasource_deployment_basic_test.go, ec/acc/testdata/datasource_deployment_basic.tf, ec/ecdatasource/deploymentsdatasource/expanders.go, ec/ecdatasource/deploymentsdatasource/expanders_test.go
Fixes a bug where the name prefix query was using a text field rather
than a keyword field in order to ensure the query is not analyzed.
Additionally the acceptance tests have been fixed since recently it
appears the deployment read API returns all possible topology elements
even if the size is set to 0. This means that the `ec_deployment` datasource
will return more topology elements than what is set in the `ec_deployment`
resource. I will open up a follow up PR with the fix for this, but I wanted to 
leave the tests passing for now.
Closes: https://github.com/elastic/terraform-provider-ec/issues/239
Manually and through acceptance tests
=> ec_deployments: Bugfix for queries with hyphens

docs/data-sources/ec_deployments.md, ec/acc/datasource_tags_test.go, ec/acc/testdata/datasource_tags.tf, ec/ecdatasource/deploymentsdatasource/expanders.go, ec/ecdatasource/deploymentsdatasource/expanders_test.go, ec/ecdatasource/deploymentsdatasource/schema.go
This PR attempts to allow filtering by "tags" when using the `ec_deployments` datasource.
For example:
```hcl
data "ec_deployments" "example" {
elasticsearch {
healthy = "true"
}
tags = {
"foo" = "bar"
}
}
output "test" {
value = data.ec_deployments.example.deployments
}
```
```bash
> terraform output test                 
tolist([
{
"apm_resource_id" = "ba049aec4b0249818af25c7ef7543ba9"
"deployment_id" = "10974c2d7136235d8fe88be9545a8d22"
"elasticsearch_resource_id" = "fbeaf8097f1342dbb4cf25aea4310796"
"enterprise_search_resource_id" = "dab52337b8414f57a4b5f40fb9c7ffb3"
"kibana_resource_id" = "6f7a0a51fa584ace8be97845c50d6525"
},
])
```
.... where `10974c2d7136235d8fe88be9545a8d22` is tagged with `{ "foo" = "bar"}` and is elasticsearch-healthy !
Closes #182 
- Unit test …
=> Filter ec_deployments datasource by tags

.changelog/208.txt, .changelog/209.txt, .changelog/216.txt, .changelog/218.txt, .changelog/235.txt, .changelog/238.txt, .changelog/241.txt, .changelog/242.txt, .changelog/244.txt, .changelog/248.txt, .changelog/253.txt, .github/workflows/changelog_generation.yml, CHANGELOG.md, Makefile, README.md, build/Makefile.deps, build/Makefile.release, docs/index.md, ec/version.go, examples/deployment/deployment.tf, examples/deployment_ccs/deployment.tf, examples/deployment_ec2_instance/provider.tf, examples/deployment_with_init/provider.tf, examples/extension_bundle/extension.tf, scripts/changelog.tmpl, scripts/generate-changelog.sh, scripts/release-note.tmpl
Adds a changelog generator inspired on the work Hashicorp has done for
some of their providers. The structure is as follows:
Each change (PR) worth having an entry in the changelog should add a new
file `#PR.txt` as part of the Pull request. Examples on the file format
can be found in the `.changelog` folder.
Also, adds a GitHub action that will run every time a PR is merged and
run `make changelog` and commit any changes should there be any new
entries to the changelog file.
Last, I've ran the changelog generation for the upcoming version and
bumped the current provider version to `v0.1.0`.
Have the changelog automatically generated.
By running `make changelog`.
=> scripts: Add changelog generator

README.md, docs/index.md, docs/resources/ec_deployment.md, docs/resources/ec_deployment_traffic_filter.md
Updates all the documentation examples to use the `ec_stack` datasource
to avoid stale stack versions from being present in our examples.
#256
=> docs: Update doc examples to use stack datasource

.github/workflows/changelog_generation.yml
Adds the missing GITHUB_TOKEN env to the step that runs `git commit` and git push.
=> changelog: Add GITHUB_TOKEN to git commit step

ec/acc/datasource_deployment_basic_test.go, ec/acc/datasource_stack_test.go, ec/acc/datasource_tags_test.go, ec/acc/deployment_basic_defaults_test.go, ec/acc/deployment_basic_test.go, ec/acc/deployment_ccs_test.go, ec/acc/deployment_extension_basic_test.go, ec/acc/deployment_extension_bundle_file_test.go, ec/acc/deployment_extension_plugin_download_test.go, ec/acc/deployment_hotwarm_test.go, ec/acc/deployment_observability_test.go, ec/acc/deployment_traffic_filter_association_test.go, ec/acc/deployment_traffic_filter_test.go, go.mod
Requires the module to use Go 1.16.x and removes any usages of the
`io/ioutil` deprecated library.
=> go: Require 1.16 and remove deprecated io/ioutil

.changelog/300.txt, docs/data-sources/ec_deployments.md, ec/ecdatasource/deploymentsdatasource/expanders.go, ec/ecdatasource/deploymentsdatasource/expanders_test.go, ec/ecdatasource/deploymentsdatasource/schema.go, examples/deployment/deployment.tf
Adds a new `size` integer parameter to the `ec_deployments` data source
which allows users to specify a maximum number of deployments to be
returned. The API defaults to 10 and the provider defaults to `100`.
Closes #294
=> ec_deployments: Add size parameter to data source 

.changelog/308.txt, ec/ecresource/deploymentresource/delete.go, ec/ecresource/deploymentresource/delete_test.go
Adds retries when the plan tracking message of a deployment shutdown
contains the Timeout Exceeded message, with a maximum of 3 retries.
No more failures on flakey `Timeout Exceeded`.
Acceptance tests.
=> ec_deployment: Retry destroy on Timeout Exceeded

.changelog/309.txt, ec/acc/deployment_fixture_test.go, ec/acc/deployment_snapshot_test.go, ec/acc/testdata/deployment_snapshot_1.tf, ec/acc/testdata/deployment_snapshot_2.tf, ec/ecresource/deploymentresource/elasticsearch_expanders.go, ec/ecresource/deploymentresource/expanders.go, ec/ecresource/deploymentresource/expanders_test.go
Fixes a bug where the strategy field wasn't set on either of the create
or update operations and it made restoring a snapshot on an existing
deployment impossible since when `transient.snapshot_restore.strategy`
isn't set, the API will make it default to "full", which isn't a valid
restoration strategy for snapshots when a deployment has already been
created and it's running, for the operation to succeed, "partial" must
be used.
Closes #249
Manual, unit and acceptance tested.
=> ec_deployment: Set snapshot restore strategy to `partial` on Update

docs/resources/ec_deployment.md
Adds `frozen` and `ml` to the list of available data tiers for the `elasticsearch.topology` block.
Closes: https://github.com/elastic/terraform-provider-ec/issues/317
Stay up to date!
N/A
=> docs: data tiers update

.changelog/322.txt, ec/ecdatasource/deploymentsdatasource/expanders.go, ec/ecdatasource/deploymentsdatasource/expanders_test.go
Uses the `Sort` field of the Search body request to always sort the
resulting deployments by ID, since they were not, now it should ALWAYS
return the same result order as long as the deployment array doesn't
change.
Closes #320
=> ec_deployments: Use API sorting by deployment ID

.changelog/324.txt, docs/resources/ec_deployment.md, ec/acc/deployment_basic_test.go, ec/ecresource/deploymentresource/elasticsearch_expanders.go, ec/ecresource/deploymentresource/elasticsearch_flatteners.go, ec/ecresource/deploymentresource/expanders_test.go, ec/ecresource/deploymentresource/flatteners_test.go, ec/ecresource/deploymentresource/import_test.go, ec/ecresource/deploymentresource/schema_elasticsearch.go, ec/ecresource/deploymentresource/testutil_func.go
This patch adds the necessary logic to handle both account and external
trust settings, allowing users to set up their own trust settings for
an Elasticsearch cluster.
It also fixes the unfortunate bug where the default account trust is
unset by the provider on any update operation.
Closes #323.
=> ec_deployment: Handle account and external trust

ec/acc/deployment_post_node_role_upgrade_test.go, ec/acc/testdata/deployment_post_node_roles_upgrade_1.tf, ec/acc/testdata/deployment_post_node_roles_upgrade_2.tf, ec/acc/testdata/deployment_pre_node_roles_migration_3.tf, ec/ecresource/deploymentresource/expanders.go, ec/ecresource/deploymentresource/expanders_test.go
Fixes a bug that prevents deployments from upgrading when they're using
the `node_roles` field in the state.
The reason was that since the "version" field was changing, the template
field that was being chosen was `node_type_*` instead of `node_roles`.
Adds an integration test covering this scenario which was  missing, this
being the main reason why we shipped this bug with `0.2.0`.
Closes #328
=> ec_deployment: Fix bug on upgrade with node_roles

ec/ecresource/deploymentresource/expanders.go, ec/ecresource/deploymentresource/expanders_test.go
Fixes a bug where the deployment alias field is ignored in the update
requests.
Closes #338
=> ec_deployment: Fix bug where alias is ignored

.changelog/361.txt, ec/ecresource/deploymentresource/elasticsearch_expanders.go, ec/ecresource/deploymentresource/elasticsearch_flatteners.go, ec/ecresource/deploymentresource/elasticsearch_flatteners_test.go, ec/ecresource/deploymentresource/expanders_test.go, ec/ecresource/deploymentresource/flatteners_test.go, ec/ecresource/deploymentresource/schema_elasticsearch.go
Handles the `plan.topology.[].elasticsearch` object as a computed block
that will be flattened (stored) in the state and expanded when present.
This solves the problem where the UI (used to) set these settings at the
topology level and the Terraform Provided set them at the Elasticsearch
level. It still doesn't allow users to set them at the topology level
since that's not the desired behavior, but with after change it will not
unset those fields with every plan change anymore, resulting in less
disruptive behavior.
Resolves #214
=> ec_deployment: Avoid unsetting Elasticsearch topology configuration

.changelog/362.txt, docs/data-sources/ec_deployments.md, ec/acc/datasource_deployment_basic_test.go, ec/ecdatasource/deploymentdatasource/datasource.go, ec/ecdatasource/deploymentsdatasource/datasource.go, ec/ecdatasource/deploymentsdatasource/datasource_test.go, ec/ecdatasource/deploymentsdatasource/schema.go
Adds two new fields, `deployments.#.name` and `deployments.#.alias` to
the `ec_deployments` datasource.
Part of #357
Unit and Acceptance tested.
=> ds/ec_deployments: Add `name` and `alias` fields

.github/workflows/changelog_generation.yml
Adds a conditional to skip running the changelog_generation job when the
push event occurs on a PR reference.
Prevents the job from running since it fails.
=> github actions: skip changelog_generation on PRs

.github/workflows/changelog_generation.yml
The change introduced in #366 turned off changelog generation for all
the runs, this attempts to turn the changelog generation back on,
since the intention was to only disable them for pull requests.
=> github action: Turn changelog generation back on

.changelog/371.txt, ec/acc/deployment_failed_upgrade_retry_test.go, ec/acc/testdata/deployment_upgrade_retry_1.tf, ec/acc/testdata/deployment_upgrade_retry_2.tf, ec/ecresource/deploymentresource/flatteners.go, ec/ecresource/deploymentresource/flatteners_test.go
Reconciles the top level `ec_deployment.version` field to the lesser of
all of the resource versions. Cases where the version is updated and one
or more of the resources did not succeed to upgrade, were not detected
since the `version` field was not reconciled during the Read stage and
was set to the value the terraform configuration was set to without the
ability to detect drift.
Failed upgrades could not be retried through the provider.
Unit and acceptance tested.
=> ec_deployment: Persist lowest resource `version`

ec/acc/deployment_docker_image_override_test.go, ec/acc/testdata/deployment_docker_image_override.tf, ec/ecresource/deploymentresource/apm_expanders.go, ec/ecresource/deploymentresource/apm_flatteners.go, ec/ecresource/deploymentresource/elasticsearch_expanders.go, ec/ecresource/deploymentresource/elasticsearch_flatteners.go, ec/ecresource/deploymentresource/enterprise_search_expanders.go, ec/ecresource/deploymentresource/enterprise_search_flatteners.go, ec/ecresource/deploymentresource/expanders_test.go, ec/ecresource/deploymentresource/flatteners_test.go, ec/ecresource/deploymentresource/kibana_expanders.go, ec/ecresource/deploymentresource/kibana_flatteners.go, ec/ecresource/deploymentresource/schema_apm.go, ec/ecresource/deploymentresource/schema_elasticsearch.go, ec/ecresource/deploymentresource/schema_enteprise_search.go, ec/ecresource/deploymentresource/schema_kibana.go
Adds a new `config.docker_image` argument to all resources which allows
Elastic Cloud internal users to override the docker image used.
**This is an internal only field, and attempting to set it to any value
when you're not part of the Elastic org, will result in an API error**.
Better support for docker image overrides.
Unit and acceptance tested
=> ec_deployment: Add `config.docker_image` argument

README.md, build/Makefile.version, scripts/update-provider-version.sh
Adds a new script which will be called after each version bump, which
will update all the `terraform.ec.version` references to use the version
which was just bumped. This script will be called every time a new tag
is pushed and thus will maintain all the versions in sync.
This solves an issue where the version would be updated, but the main
`README.md` and the examples would still point to the version which was
just released.
Outdated readme and examples.
<details>
<summary>Testing instructions</summary>
```
$ echo 'diff --git a/Makefile b/Makefile
index 45c0e42..9860a66 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
SHELL := /bin/bash
export GO111MODULE ?= on
-export VERSION := 0.3.0-dev
+export VERSION := 0.2.1-dev
export BINARY := terraform-provider-ec
export GOBIN = $(shell …
```
=> scripts: Update provider blocks with version

ec/ecresource/deploymentresource/delete.go, ec/ecresource/deploymentresource/delete_test.go
Adds the string `Some instances were not stopped` that happens quite
frequently as a retryable error on the destroy step. Should improve the
test pass rate and reduce transient errors. It's still bound by a max
of 3 retries.
By running the acceptance tests.
=> ec_deployment: retry deallocation error on destroy

docs/resources/ec_deployment_traffic_filter.md
Adds documentation for how to add a GCP Private Service Connect traffic
filter. Also updates the deployment templates to match the ones that are
actually defined in each of the cloud regions.
Document how to add a traffic rule for PSC.
Manually.
=> ec_deployment_traffic_filter: Add GCP PSC docs

ec/ecresource/deploymentresource/elasticsearch_expanders.go, ec/ecresource/deploymentresource/expanders_test.go, ec/version.go
Fixes SIGSEGV error triggered by nil pointer dereferenced under certain conditions. Some of these conditions are listed in [407](https://github.com/elastic/terraform-provider-ec/issues/407).
After importing an ec_deployment resource with configuration blocks inside topology blocks for elasticsearch, such as user_settings_yaml inside a master topology configuration block, into Terraform, every change to that configuration will trigger a SIGSEGV as a nil pointer is dereferenced. This change fixes the issue by initialising that pointer when needed. 
https://github.com/elastic/terraform-provider-ec/issues/407
Modifying some ec_deployment resources after importing them into Terraform fails with a SIGSEGV (see issue above).
Added unit test. 
- [] All new and existing tests passed
=> fix: 407 sigsegv when modifying topologies config

ec/acc/deployment_snapshot_test.go
Skips the test for now since it seems to be failing quite often and it
makes it difficult to rely on the acceptance tests for PR checks.
Part of #443
=> acceptance: Skip Deployment_snapshot_restore test

CONTRIBUTING.md, build/Makefile.build, main.go
Add -debug option and related code to allow debugger-based debugging to use with a tool like delve to inspect what is happening in a provider as it is happening.
A detailed explanation is available in this section of the Terraform plugin sdk documentation:
[debugger-based-debugging](https://www.terraform.io/plugin/sdkv2/debugging#debugger-based-debugging)
https://github.com/elastic/terraform-provider-ec/issues/429
It allows investigating some issues easily. 
Issue investigation. See linked issue https://github.com/elastic/terraform-provider-ec/issues/429
=> feat: 429 add debug mode

ec/ecresource/deploymentresource/elasticsearch_expanders.go, ec/ecresource/deploymentresource/elasticsearch_expanders_test.go
This fixes an issue when specifying an autoscaling min/max when there is no corresponding min/max defined in the deployment template. 
We're unable to specify a default in the Terraform schema since the resource attributes are `Computed`. Instead we define a default in code. 
Fixes https://github.com/elastic/terraform-provider-ec/issues/401
Unit tests
Manually with:
```
resource "ec_deployment" "staging" {
region                 = "eu-west-1"
deployment_template_id = "aws-storage-optimized"
version = "7.17.3"
elasticsearch {
topology {
id         = "hot_content"
size       = "2g"
zone_count = 3
autoscaling {
max_size = "8g"
}
}
topology {
id         = "warm"
size       = "2g"
zone_count = 2
autoscaling {
max_size = "15g"
min_size = "4g"
}
}
}
}
```
=> Provide a default for the autoscaling min/max resource

.github/workflows/changelog_generation.yml
Looking at the commit history, we can see multiple `Update CHANGELOG.md and NOTICE` commits in short succession, for example: 
This change forces the changelog gen workflow to ignore commits which only include files touched by the changelog gen workflow to short circuit these cycles.
=> Don't fire the changelog generation workflow in response to the changlog generation workflow

.changelog/507.txt, docs/resources/ec_deployment.md, ec/ecresource/deploymentresource/elasticsearch_expanders.go, ec/ecresource/deploymentresource/elasticsearch_expanders_test.go, ec/ecresource/deploymentresource/import_test.go, ec/ecresource/deploymentresource/schema_elasticsearch.go, ec/version.go
The current implementation uses `autodetect` configuration strategy, this strategy is fine in most cases. This PR allows to choose the configuration strategy from a set of pre-configured strategies.
In our case we use SNAPSHOT versions and this strategy does not work as expected when we changed the Docker image for a new SNAPSHOT version, we need to perform a `rolling` with `groupBy` to `__all__` to perform a stop and start of all nodes at the same time to avoid version conflicts.
I have made a manual test and the PR includes some unit tests.
=> Elasticsearch configuration strategy support

docs/resources/ec_deployment.md, ec/acc/deployment_observability_self_test.go, ec/acc/testdata/deployment_observability_self.tf, ec/ecresource/deploymentresource/observability.go, ec/ecresource/deploymentresource/observability_test.go, ec/ecresource/deploymentresource/schema.go
Passing 'self' as the deployment-id is considered the same as the actual deployment-id of the resource itself. Adjusts the diff-calculation to always map 'self' to the current deployment-id. When creating the deployment, the value stays as 'self' since the deployment-id will only be known after creation.
I updated the docs to show this new capability, but might need some improvement. It is now possible to use the following config
```
observability {
deployment_id: "self"
}
```
To directly enable self-monitoring even when creating a deployment
Fixes https://github.com/elastic/terraform-provider-ec/issues/333
=> Observability: Handle passing 'self' as target deployment-id.

build/Makefile.test
This should be reverted once https://github.com/hashicorp/terraform-plugin-sdk/issues/1073 is fixed
=> Run acceptance tests in CI against 1.2.9

build/Makefile.tools
The version in use is a couple of years old and this works around a local issue @webfella was having.
=> Bump terrafmt version

.changelog/534.txt, ec/ecresource/deploymentresource/apm_expanders.go, ec/ecresource/deploymentresource/apm_expanders_test.go, ec/ecresource/deploymentresource/elasticsearch_expanders.go, ec/ecresource/deploymentresource/elasticsearch_expanders_test.go, ec/ecresource/deploymentresource/enterprise_search_expanders.go, ec/ecresource/deploymentresource/enterprise_search_expanders_test.go, ec/ecresource/deploymentresource/integrations_server_expanders.go, ec/ecresource/deploymentresource/integrations_server_expanders_test.go, ec/ecresource/deploymentresource/kibana_expanders.go, ec/ecresource/deploymentresource/kibana_expanders_test.go, ec/ecresource/deploymentresource/observability.go, ec/ecresource/deploymentresource/observability_test.go, ec/ecresource/trafficfilterresource/expanders.go, ec/ecresource/trafficfilterresource/expanders_test.go, ec/internal/util/parsers.go
Repro in the linked issue. 
Some fields may be sourced from Terraform variables, if those variables are optional then it's not uncommon to explicitly set fields to null, which the provider should treat as if the field was left unset. 
Fixes https://github.com/elastic/terraform-provider-ec/issues/522
Unit tests
Manually
=> Check type casts to void crashing when casting explicit null values

.changelog/548.txt, docs/resources/ec_deployment.md, ec/acc/deployment_integrations_server_test.go, ec/ecresource/deploymentresource/integrations_server_flatteners.go, ec/ecresource/deploymentresource/integrations_server_flatteners_test.go, ec/ecresource/deploymentresource/schema_integrations_server.go
Closes https://github.com/elastic/terraform-provider-ec/issues/393
Unit test, acceptance tests
=> Explicitly capture apm and fleet endpoints as part of the integrations server schema

build/Makefile.test
Reverts elastic/terraform-provider-ec#542
Testing against 1.3+ should work with [this](https://github.com/elastic/terraform-provider-ec/pull/549) SDK update.
=> Revert "Run acceptance tests in CI against 1.2.9"

docs/resources/ec_deployment_traffic_filter.md, ec/ecresource/trafficfilterresource/schema.go
The Traffic Filter resource docs include an [example](https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment_traffic_filter#gcp-private-service-connect-type) of the "GCP Private Service Connect type", but it was not listed in the argument reference for [`type`](https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment_traffic_filter#type).
Including this in the documentation gives confidence to the user that GCP Private Service Connect is supported by the provider and helps them use it correctly.
I copied the value from my working Terraform code where I have a working Traffic Filter for GCP PSC. It also reflects the [documented example](https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment_traffic …
=> docs: Add GCP PSC to Traffic Filter argument reference for type

.changelog/547.txt, ec/acc/deployment_template_migration_test.go, ec/acc/testdata/deployment_basic_defaults_hw_2.tf, ec/ecresource/deploymentresource/apm_expanders.go, ec/ecresource/deploymentresource/elasticsearch_expanders.go, ec/ecresource/deploymentresource/enterprise_search_expanders.go, ec/ecresource/deploymentresource/expanders.go, ec/ecresource/deploymentresource/expanders_test.go, ec/ecresource/deploymentresource/integrations_server_expanders.go, ec/ecresource/deploymentresource/kibana_expanders.go, ec/ecresource/deploymentresource/testdata/deployment-update-aws-cross-cluster-search-v2.json, ec/ecresource/deploymentresource/testutil_func.go
Use the migrate template API to build the base update request when an existing deployment changes.  `deployment_template_id`, 
Fixes https://github.com/elastic/terraform-provider-ec/issues/487
Fixes https://github.com/elastic/terraform-provider-ec/issues/556
This API is purpose built to update deployment options to be compatible with a different template and simplifies the process for migrating deployments between hardware types. 
Manually, acceptance test, unit tests
=> Utilise the migrate template API when applying changes to the deployment template id 

docs/data-sources/ec_gcp_private_service_connect_endpoint.md
Typo fix in GCP PSC datasource documentation. It currently incorrectly references Azure.
N/A
It's a typo.
N/A
=> Fix typo in GCP PSC datasource documentation

docs/data-sources/ec_stack.md
Fixes https://github.com/elastic/terraform-provider-ec/issues/593
Essentially copies the note from the `ec_deployment` resource docs, linking through to the list of available regions.
=> Link through to the ESS region list in the ec_stack docs

build/Makefile.test
Fix the CI testing version so we have accurate test results whilst the underlying issues are fixed
Related to https://github.com/elastic/terraform-provider-ec/issues/599
=> Changes introduced in 1.4 lead to infinite diff loops with this provider

.changelog/613.txt, docs/resources/ec_snapshot_repository.md, ec/ecresource/snapshotrepositoryresource/create.go, ec/ecresource/snapshotrepositoryresource/delete.go, ec/ecresource/snapshotrepositoryresource/read.go, ec/ecresource/snapshotrepositoryresource/resource_test.go, ec/ecresource/snapshotrepositoryresource/schema.go, ec/ecresource/snapshotrepositoryresource/update.go, ec/provider.go, go.mod, go.sum
This adds a new resource `ec_snapshot_repository` for usage with ECE.
#608 
There is currently no way to create cluster level snapshot repositories in ECE via terraform.
- There are extensive unit tests with high coverage.
- There are no acceptance tests, as this functionality is not available on ESS.
- I tested this against our own ECE dev instance manually.
→ I did not run acceptance tests, but there are no changes that effect any of the existing functionality.
→ I think the failing unit tests are related to https://github.com/elastic/terraform-provider-ec/issues/599 and are not caused by the changes in this PR.
=> Add resource ec_snapshot_repository

docs/resources/deployment.md, ec/acc/deployment_basic_test.go, ec/acc/testdata/deployment_basic_reset_password.tf, ec/ecresource/deploymentresource/deployment/v2/deployment_create_payload.go, ec/ecresource/deploymentresource/deployment/v2/deployment_read.go, ec/ecresource/deploymentresource/deployment/v2/schema.go, ec/ecresource/deploymentresource/read.go, ec/ecresource/deploymentresource/update.go
Adds a `reset_elasticsearch_password` attribute to the deployment resource, when true this explicitly resets the password, updating the value in state with the new credentials. 
Fixes https://github.com/elastic/terraform-provider-ec/issues/99
With the migration to 0.6 and higher requiring re-importing existing deployments, which in turn does not include the current elastic user, customers need a path to programatically update the credentials in TF state.  
Acceptance tests, manual tests.
=> Reset es password

.changelog/632.txt, docs/resources/deployment.md, ec/acc/deployment_basic_test.go, ec/acc/deployment_traffic_filter_association_test.go, ec/acc/testdata/deployment_basic_with_empty_traffic_filter.tf, ec/ecresource/deploymentresource/deployment/v2/deployment_read.go, ec/ecresource/deploymentresource/deployment/v2/schema.go, ec/ecresource/deploymentresource/read.go, ec/ecresource/deploymentresource/update.go
Marks the ec_deployment traffic_filter attribute as computed, since it can also be managed via a ec_deployment_traffic_filter_association resource. 
Fixes https://github.com/elastic/terraform-provider-ec/issues/621
Fixes https://github.com/elastic/terraform-provider-ec/issues/419
Manually, acceptance tests
=> Deployment traffic filters are computed to not conflict with a traffic filter association resource

.changelog/667.txt, ec/acc/datasource_deployment_basic_test.go, ec/acc/testdata/datasource_deployment_basic.tf, ec/ecdatasource/deploymentdatasource/flatteners_elasticsearch.go
When no autoscaling fields are defined, the autoscaling property on the model will be nil (with nil ElemType), causing the provider to crash. This PR sets the initial value to a NullList with the correct ElemTypes set. 
Fixes https://github.com/elastic/terraform-provider-ec/issues/649
Manually, added an acceptance test.
=> Support deployments without autoscaling fields defined in the deployments data source

.changelog/683.txt, ec/ecresource/deploymentresource/deployment/v2/schema.go, ec/ecresource/deploymentresource/deployment/v2/version_validator.go, ec/ecresource/deploymentresource/deployment/v2/version_validator_test.go, ec/ecresource/deploymentresource/elasticsearch/v2/node_roles_validator.go, ec/ecresource/deploymentresource/elasticsearch/v2/node_roles_validator_test.go, ec/ecresource/deploymentresource/elasticsearch/v2/node_types_validator.go, ec/ecresource/deploymentresource/elasticsearch/v2/node_types_validator_test.go, ec/ecresource/deploymentresource/elasticsearch/v2/schema.go, ec/ecresource/deploymentresource/utils/definitions.go
Applying incompatible changes without this validation leads to confusing, esoteric errors (detailed in https://github.com/elastic/terraform-provider-ec/issues/663). This PR instead aims to provide a clearer error for end users. 
Fixes https://github.com/elastic/terraform-provider-ec/issues/663
Unit tests, manually.
=> Validate node_roles and node_types are supported in the version used

ec/ecresource/deploymentresource/deployment/v2/deployment_read.go, ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_payload.go, ec/ecresource/trafficfilterresource/schema.go, ec/internal/validators/urlvalidator.go, go.mod
Go 1.21 introduced the new slices package to replace x/exp/slices. Migrate to slices and drop the dependency
Closes https://github.com/elastic/terraform-provider-ec/issues/737
https://go.dev/doc/go1.21#slices
=> build: replace x/exp package with stdlib slices packages

.buildkite/hooks/pre-command, .buildkite/release.sh, .buildkite/release.yml, .ci/pipelines/release.Jenkinsfile, .goreleaser.yml, build/Makefile.release, developer_docs/RELEASE.md
Migrate the Jenkins [Release pipeline](https://github.com/elastic/terraform-provider-ec/blob/master/.ci/pipelines/release.Jenkinsfile) to Buildkite.
Notes:
* I moved all the logic to load the GPG keys into the pre-command hook to benefit from secrets redaction features and move away from the file based approach used in the `.ci/Makefile`
* With the above point, I had to rename an env. variable to `GPG_FINGERPRINT_SECRET` instead of `GPG_FINGERPRINT` so that Buildkite would always redact it and we don't risk leaking it (with a set -x or printenv). I don't think it would affect anyone since this is used only in the CI flow.
* The k8s agent used for the build is rather big (`cpu: "8" memory:"32G") but it seems needed as go-releaser is very hungry on cross-compiling all the targets in …
=> Setup the Release pipeline

.changelog/749.txt, ec/ecresource/extensionresource/schema.go
Fixes https://github.com/elastic/terraform-provider-ec/issues/748
Unit/acceptance
=> Set size to unknown if other extension attributes change

.changelog/752.txt, ec/acc/deployment_basic_test.go, ec/ecresource/deploymentresource/update.go
Resetting the credentials of imported resources should result in the username being set as well as the password.
=> Set the username when resetting the elastic password

.changelog/777.txt, ec/ecresource/deploymentresource/deployment/v2/schema.go
When resetting the password on an imported deployment we set the username along with the password, prior to this PR this caused the provider to blow up. 
Fixes https://github.com/elastic/terraform-provider-ec/issues/766
Manually, it's hard to add an acceptance test here since it requires importing the existing deployment.
=> Set username to unknown when resetting password

.changelog/783.txt, ec/ecresource/deploymentresource/integrationsserver/v2/integrations_server_payload.go, ec/ecresource/deploymentresource/integrationsserver/v2/integrations_server_read.go, ec/ecresource/deploymentresource/integrationsserver/v2/integrations_server_read_test.go, ec/ecresource/deploymentresource/integrationsserver/v2/schema.go
The `profiling` and `symbols` endpoints were not being read from the response payload, ~causing an error~.
When activating universal profiling in Kibana (`/app/profiling` in Kibana), several new endpoints are added to the deployment:
These were not recognized by the provider, ~leading to a deadlock situation where the deployment cannot be administered through terraform anymore. This PR fixes this problem~. This PR adds the ability to correctly parse the endpoints in the response.
~Fixes https://github.com/elastic/terraform-provider-ec/issues/781~
The related issue is fixed in 0.6+.
See the above description.
Unit tested.
AFAICT there's no acceptance test covering this, it might make sense to write one though?
I've also ran the setup described in the issue linked above, and was able to …
=> Fixed error when universal profiling is activated

.changelog/788.txt, ec/ecresource/deploymentresource/deployment/v2/deployment_read.go, ec/ecresource/deploymentresource/deployment/v2/deployment_read_test.go, ec/ecresource/deploymentresource/elasticsearch/v2/schema.go, ec/ecresource/deploymentresource/read.go
Since the `snapshot_name` is computed we must persist it in the response from read. This PR ensures that any configured value is maintained through the read cycle. 
Fixes https://github.com/elastic/terraform-provider-ec/issues/787
Manually
=> Persist snapshot source in the read response

.changelog/797.txt, CONTRIBUTING.md, docs/data-sources/deployments.md, docs/resources/deployment.md, ec/acc/datasource_deployment_basic_test.go, ec/acc/testdata/datasource_deployment_basic.tf, ec/ecdatasource/deploymentsdatasource/datasource.go, ec/ecdatasource/deploymentsdatasource/expanders.go, ec/ecdatasource/deploymentsdatasource/expanders_test.go, ec/ecdatasource/deploymentsdatasource/schema.go
- Extends the ec_deployments data source with an additional filter `name`
- Using this parameter will search for deployments with this exact name (uses an ES term query internally)
- As an alternative to `name_prefix` that searches by a prefix.
https://github.com/elastic/terraform-provider-ec/issues/639
=> datasource/deployments: Filter by name.

.github/CODEOWNERS
The team was renamed to `control-plane-stateful-applications`. This way the right people are added as reviewers.
@tobio If you want I can also add you here so you are still added as reviewer to new PRs. (But I can also remove you if the notifications are annoying).
=> Update CODEOWNERS with new team name

.buildkite/acceptance_pipeline.yml
The step currently has a key of "" so the `pre-exit` code never runs (Referenced in `.buildkite/hooks/pre-exit`). This leads to old acceptance-test deployments piling up over time.
With this change the step should run after the tests and clean up hanging deployments.
=> Fix acceptance pipeline cleanup.

ec/ecresource/deploymentresource/elasticsearch/v2/node_types_validator.go, ec/ecresource/deploymentresource/elasticsearch/v2/node_types_validator_test.go
Fixes an error in the validation when using legacy node-type configs.
If the version is unset, the validation crashes with an error. This can happen in certain scenarios: When using a reference (e.g. `data.ec_stack.latest.version`) it will not be resolved in a first phase when this validation is called. In such cases the validation should be skipped.
The validation still works as it is called again after the reading phase when the field has been resolved.
https://github.com/elastic/terraform-provider-ec/issues/734
=> Bugfix: node-types-validation should handle empty stack version.

.buildkite/release.sh
The 0.11.0 release failed due to `jq` missing.
```
modify_spec.sh: 3: jq: not found
go: downloading github.com/hashicorp/terraform-plugin-codegen-framework v0.4.0
time=2024-08-28T11:45:58.017Z level=ERROR msg="error executing command" err="error validating IR JSON: invalid JSON"
exit status 1
ec/internal/gen/serverless/serverless.go:20: running "go": exit status 1
make[1]: *** [build/Makefile.build:14: gen] Error 1
```
- `jq` is now needed to run the script `modify_spec.sh`
- Since the release runs from the `docker.io/library/golang:1.22` image, it doesn't have jq installed
- as a workaround, the release script now installs jq first
- We could also prepare a dedicated build-image that contains jq, but as we release very rarely, I think it is fine to just install jq for now.
=> Install jq before releasing.

.buildkite/hooks/pre-command
The currently used GITHUB_TOKEN has expired and can't be used anymore, instead we now use an ephemeral token provided with every build. The `VAULT_GITHUB_TOKEN` is created fresh for every build and injected automatically (similar to the github token provided in github actions)
We did the same thing for the elasticstack provider:
https://github.com/elastic/terraform-provider-elasticstack/pull/712
=> Use ephemeral github token.

.changelog/858.txt, ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_keystore_contents.go, ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_payload.go, ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_payload_test.go, ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_snapshot.go
- This ensures the settings are only put into the update request if there are actual changes in the config
- Otherwise the settings are left out of the payload
- This solves a bug where every apply would reset the policy back to the default (because putting the default settings in the plan will cause it to reset the policy).
- When using the elasticstack provider to manage the policy, we want the ec provider to not touch it.
https://github.com/elastic/terraform-provider-ec/issues/854
=> Bugfix: Only pass snapshot settings into the update plan if there are changes

.changelog/859.txt, ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_keystore_contents.go, ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_payload.go, ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_payload_test.go
The trust setting should only be added to the payload when they change. If they are left out of the payload, no changes to the trust will be made.
This is a partial fix/workaround for https://github.com/elastic/terraform-provider-ec/issues/842 
https://github.com/elastic/terraform-provider-ec/issues/842
=> Elasticsearch trust settings: Only add them to the update payload if there are changes.

examples/deployment_ec2_instance/provider.tf
Workaround for https://github.com/hashicorp/terraform-provider-aws/issues/39676
Currently Git tests fail with version v5.71.0 and as such no merges are possible to the ec provider main branch.
We need to be able to merge.
=> Workaround for AWS provider SHA error

ec/provider.go
This removes validators.Known() from the ec.endpoint parameter.
This will allow setting ec.endpoint as a variable and prevents an error "Value must be known" during terraform plan
We want to dynamically change the endpoint URL using variables during CI/CD deployments.
It is currently not possible because during terraform plan **ec.endpoint** is not filled with the given variable:
```
provider "ec" {
endpoint = var.ECE_CONSOLE_URL
apikey = var.ECE_CONSOLE_API_KEY
}
```
local.auto.tfvars:
```
ECE_CONSOLE_URL = "https://console.ece.mydomain.com"
ECE_CONSOLE_API_KEY = "myapikey"
```
The endpoint field is also declared as [optional ](https://github.com/elastic/terraform-provider-ec/blob/6f6c1b81b05316c7959039f6320e67dd10de173e/ec/provider.go#L134) in the code and according to [documentation …
=> Remove validators.Known() on endpoint.

ec/acc/deployment_basic_defaults_test.go, ec/acc/deployment_cpu_optimized_test.go, ec/internal/planmodifiers/use_state_unless_template_changed.go, ec/internal/planmodifiers/use_state_unless_template_changed_test.go
If a computed attribute parent state is null, don't try to use the state to avoid inconsistency errors when the apply process finishes the state will still be used in the previous cases to preserve the same functionality.
https://elasticco.atlassian.net/browse/CP-9334
We found a bug while fixing the acceptance tests where multiple stateless components have this inconsistent behavior, in the eyes of terraform this is a bug.
> The New State object returned from the provider must meet the following constraints:
> * Any attribute that had a known value in the Final Planned State must have an identical value in the new state. In particular, if the remote API returned a different serialization of the same value then the provider must preserve the form the user wrote in the configuration, and …
=> bugfix: don't use nil state for a computed attribute

.github/CODEOWNERS
Corresponds with GH team name change: https://github.com/orgs/elastic/teams/control-plane-hosted-applications
=> Rename stateful applications to hosted applications

docs/resources/deployment.md
Update the Terraform docs after the changes made in https://github.com/elastic/terraform-provider-ec/pull/874
=> chore: run `make docs-generate`

docs/resources/elasticsearch_project.md, docs/resources/observability_project.md, docs/resources/security_project.md, ec/internal/gen/serverless/resource_elasticsearch_project/elasticsearch_project_resource_gen.go, ec/internal/gen/serverless/resource_observability_project/observability_project_resource_gen.go, ec/internal/gen/serverless/resource_security_project/security_project_resource_gen.go, ec/internal/gen/serverless/serverless-project-api-dereferenced.yml, ec/internal/gen/serverless/spec-mod.json, ec/internal/gen/serverless/spec.json
When creating a new Serverless project, the password of the ES
credentials is marked as non sensitive. This means that it will be shown
in the terraform output when creating an `output` block to print it.
This commit sets the credentials.password of all Serverless resources to
sensitive, so that it is not even allowed to create a terraform `output`
block without marking it as sensitive.
As an example, for the following block:
```terraform
output "password" {
value = ec_elasticsearch_project.test.credentials.password
}
```
Before this commit, the `terraform apply` outputs the password. After
this commit, we get the following output:
```
│ Error: Output refers to sensitive values
│
│   on main.tf line 28:
│   28: output "password" {
│
│ To reduce the risk of accidentally exporting sensitive …
```
=> feat(serverless): Set the credentials.password as sensitive
